---
- name: Set facts for easier path variables
  set_fact:
    key_path: "{{ cert_directory }}/{{ cert_file_name }}.key"
    csr_path: "{{ cert_directory }}/{{ cert_file_name }}.csr"
    crt_path: "{{ cert_directory }}/{{ cert_file_name }}.crt"

- name: Make sure that pki directory exists
  become: true
  file:
    path: "{{ cert_directory }}"
    state: directory
    mode: '0755'

- name: Create cluster Certified Authority (CA)
  become: true
  community.crypto.openssl_privatekey:
    path: "{{ key_path }}"
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  become: true
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ key_path }}"
    common_name: "{{ common_name }}"
    subject_alt_name: "{{ alt_names | default(omit) }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth
      - clientAuth
  when: server_certificate

- name: Generate an OpenSSL Certificate Signing Request
  become: true
  community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ key_path }}"
    common_name: "{{ common_name }}"
    organization_name: "{{ organization | default(omit)}}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - clientAuth
  when: not server_certificate

- name: Generate an OpenSSL certificate signed with kubernetes ca
  become: true
  community.crypto.x509_certificate:
    path: "{{ crt_path }}"
    csr_path: "{{ csr_path }}"
    ownca_path: "{{ ca_crt }}"
    ownca_privatekey_path: "{{ ca_key }}"
    provider: ownca
    
