---
  - name: Pass coreDNS manifests to host
    template:
      src: coredns.yml.j2
      dest: "{{ ansible_user_dir }}/kube-dns.yml"
      mode: "0644"
    run_once: true
    delegate_to: "{{ groups['control_plane_nodes'][0] }}"

  - name: Apply coreDNS manifest file
    command: "kubectl apply -f {{ ansible_user_dir }}/kube-dns.yml"
    run_once: true
    delegate_to: "{{ groups['control_plane_nodes'][0] }}"